# Generated by Django 4.1 on 2023-08-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0005_wmslayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='wmslayer',
            name='wfs_layer_types',
            field=models.CharField(default='', help_text='WFS LayerType(s).  If there are two comma separate', max_length=200),
        ),
    ]
