# Generated by Django 4.1 on 2023-08-02 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0006_wmslayer_wfs_layer_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanetTile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_date', models.DateField(help_text='Image Date')),
                ('layer_id', models.TextField(help_text='Planet LayerID for the url template')),
            ],
        ),
    ]
