# Generated by Django 4.1 on 2023-08-11 14:34

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0011_teammember_cropping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('photo__image_field', '430x360', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='cropping'),
        ),
    ]
