# Generated by Django 4.1 on 2023-08-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0015_alter_fire_instrument'),
    ]

    operations = [
        migrations.CreateModel(
            name='NICFIAvailable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_date', models.TextField(help_text='Image YYYY-mm')),
            ],
        ),
    ]
