# Generated by Django 4.1 on 2023-08-28 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0016_nicfiavailable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='station_organization',
        ),
        migrations.DeleteModel(
            name='Measurement',
        ),
        migrations.DeleteModel(
            name='Station',
        ),
    ]
