# Generated by Django 4.1 on 2023-10-03 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0017_remove_station_station_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wmslayer',
            name='info_json',
            field=models.JSONField(blank=True, default=dict, help_text='JSON Object for UI info button and popup', verbose_name='Object for UI info button and popup'),
        ),
    ]
